# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- release
- release-msix

pool:
  vmImage: 'windows-2019'

variables:
  testImgDir: '$(System.DefaultWorkingDirectory)\FaceRecogTestFixtures'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
- stage: ReleaseStage
  displayName: ReleaseStage
  jobs:  
  - job: 'ReleaseJob'
    displayName: 'Build, Test, Publish'
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 3.1'
        inputs:
          packageType: 'sdk'
          version: '3.1.101'
      - task: DotNetCoreCLI@2
        displayName: 'Restore packages'
        inputs:
          command: 'restore'
          projects: '**\*.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: 'Build app'
        inputs:
          command: 'build'
          projects: 'Application\Application.csproj'
          arguments: '-c Release -r win-x64'
      - task: DownloadSecureFile@1
        name: faceRecogTestFixtures
        inputs:
          secureFile: 'FaceRecogTestFixtures.zip'
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '$(faceRecogTestFixtures.secureFilePath)'
          destinationFolder: '$(testImgDir)'
          cleanDestinationFolder: false
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'Domain.UnitTests/Domain.UnitTests.csproj'
          arguments: '-c Debug'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'WorkTimeAlghorithm.UnitTests/WorkTimeAlghorithm.UnitTests.csproj'
          arguments: '-c Debug'
      - task: VSTest@2
        displayName: 'Run unit tests'
        inputs:
          testImgDir: '$(testImgDir)'
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            Domain.UnitTests\**\*Tests.dll
            WorkTimeAlghorithm.UnitTests\**\*Tests.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'Infrastructure.Tests/Infrastructure.Tests.csproj'
          arguments: '-c Debug'
      - task: VSTest@2
        displayName: 'Run integration tests'
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            Infrastructure.Tests\**\*Tests.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
      - task: DotNetCoreCLI@2
        displayName: 'Run dotnet publish'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: 'Application\Application.csproj'
          arguments: '-c Release -r win-x64 -o AppRelease'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)\AppRelease'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/AppRelease.zip'
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/AppRelease.zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: GitHubRelease@1
        condition: eq(variables.isMaster, 'true')
        inputs:
          gitHubConnection: 'github.com_pekalam'
          repositoryName: 'pekalam/workTimeMonitoring'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          assets: '$(Build.ArtifactStagingDirectory)/*.zip'
          addChangeLog: false